### ISSUE TITLE
Major Bug - Unable to activate debug mode

### ISSUE THREAD

**Issue by Owizardo** [kangarko/AutoPlay#3]
Hi there in the config there is an option to enable debug like so:

```
# -------------------------------------------------------------------------------------------
# Debugging allows you to understand the plugin. It will print more messages to the console.
# Specify sections to debug, or [*] to print all out, including some special messages.
#
# Available: rotation, teleport, MobArena, leak_detector
# -------------------------------------------------------------------------------------------
Debug: []
```

It states to use [*] to print out all debugs. Doing so and reloading via /ap menu gui menu. It gives the following error: 
```

INFO 02/28/2018 22:22:23
22:22:23
Owizardo issued server command: /ap menu

22:22:26
*-----------------------------------------------*
Reloading plugin AutoPlay v1.0.9
*-----------------------------------------------*
AutoPlay // AutoPlay 1.0.9 encountered a InvalidConfigurationException! Please check your error.log and report this issue with the information in that file.
org.bukkit.configuration.InvalidConfigurationException: while scanning an alias
Console 02/28/2018 22:22:26
22:22:26
 in 'string', line 288, column 9:
    Debug: [*]
            ^
expected alphabetic or numeric character, but found ](93)
 in 'string', line 288, column 10:
    Debug: [*]
             ^
INFO 02/28/2018 22:22:26
22:22:26
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162)
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130)
	at me.kangarko.autoplay.goto.nul. .lPT8.Lpt5(SourceFile:122)
	at me.kangarko.autoplay.goto.nul. .CoM1.Lpt5(SourceFile:145)
	at me.kangarko.autoplay.goto.nul. .N.Lpt5(SourceFile:32)
	at me.kangarko.autoplay.goto.nul. .CoM1.AUX(SourceFile:59)
	at me.kangarko.autoplay.goto.nul. .cOM1.Lpt3(SourceFile:412)
	at me.kangarko.autoplay.goto.nul. .cOM1.COm2(SourceFile:387)
	at me.kangarko.autoplay.goto.nul. .A$2.AUX(SourceFile:87)
	at me.kangarko.autoplay.goto.nul. .finally.onMenuClick(SourceFile:262)
	at me.kangarko.autoplay.goto.nul. .final.onInvClick(SourceFile:61)
	at sun.reflect.GeneratedMethodAccessor502.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
AutoPlay // *-----------------------------------------------*
AutoPlay //  Error reloading AutoPlay 1.0.9
AutoPlay // *--------------------
```---------------------------*

**Comment by kangarko** [comment]
Please, when using YAML files, omit such special characters like & and * with "".

Debug: ["*"]

**Comment by Owizardo** [comment]
Just a small suggestion, you might want to correct the config file because it says to use [*] which is incorrect as per above :).

**Comment by kangarko** [comment]
Thanks, corrected!
