### ISSUE TITLE
World Mode Doesn't Work

### ISSUE THREAD

**Issue by MothGirlMusic** [kangarko/AutoPlay#7]
When put on `Mode: world` in settings theres no way to tell it what world you're using. in the GUI it says you still need it in world mode, which means this mode setting doesn't even work. 

even further, in the world mode settings, theres no way to actually set which world you're using.

```
# -------------------------------------------------------------------------------------------
# Settings for world mode. This is the mode you want to use to
# dedicate ONE ENTIRE WORLD ON YOUR SERVER to run minigames automatically.
# -------------------------------------------------------------------------------------------
World_Mode: 
  #
  # Where players should be teleported when they quit? Type the world name.
  #
  Return_World: Hub
```

i can set the return world... but i can't set the world for the plugin to use, so on load it just errors out every time. here's the error:

```
------------------------------------[ 01.02.2019 22:10:40 ]-----------------------------------
AutoPlay 1.2.15 encountered a NullPointerException
Running CraftBukkit 1.13.2-R0.1-SNAPSHOT and Java 10.0.2
Plugins: RedstoneProximitySensor v2.3.9, PlayerInteractions v1.0, BlockLocker v1.5, InfinityParkour v1.0.10, Lift v${version}, PlugMan v2.1.5, ChestSort v3.4, Recount v3.3.0, Arconix v2.0.0, TermsOfUse v1.0.0, GameAPI v1.3.5, RedstoneWaterProof v1.0 BETA, SaveRod v2.4.1, AutoPlay v1.2.15, LuckPerms v4.3.73, EasyBackup v2.8.1, DeathMessagesPrime v1.13.12, ImageMaps v0.4.5, VotingPlugin v5.17.4, FastAsyncWorldEdit v1.0, VoidGenerator v1.4.2, PerWorldPluginsPremium v1.7.5, PixelFriends v1.0, PluginConstructorAPI v1.0.50, PlayerProfiles v1.0, McWiki v2.5.1, ChatColor2 v1.7.6, PlaceholderAPI v2.9.2, AdditionsAPI v1.3.2, NametagEdit v4.4.0, TreasureHunt v3.0.5, VanillaAdditions v1.3.3, NoteBlockAPI v1.2.5, LightAPI v3.2.9, JukeBox v1.10.1, CoreProtect v2.15.1, dynmap v3.0-beta-3-160, WorldEdit v7.0.0-SNAPSHOT;4007-f3ec5bb, CityWorld v4.04, WorldBorder v1.8.7, EpicFarming v2.0.19, Votifier v2.5.0, BannerBoard v1.9.10.4, HeadsPlus v5.4, YoutubeMC v1.0, ServerMinimap v0.7.18, CS-CoreLib v9, HoloDrops v1.6, AdditionalThings v1.4.2, XrayInformer v3.7.0, The Multiverse-Core Plugin, Slimefun v9, StockPlus v1.0.13, CoreArena v1.8.1, ExtraGear v1.1.1, ExoticGarden v1.8.0, Barrels v1.12, SlimefunCustomizer v1.2.3, SlimeXpansion v1.1.11, UltimateTimber v1.0.9, ElectricSpawners v4.1, AuthMe v5.5.1-SNAPSHOT-b2200, PictureLogin v1.5, SuperLuckyBlock-Pro v2.17.1, HolographicDisplays v2.3.2, CMI v8.3.9.3, QualityArmory v1.1.135, SelectionVisualizer v2.0.2.0, TwitchSync v1.4, GadgetsMenu v4.3.4, Jobs v4.9.5, Paintball v2.2.0, MobCapture v1.2.6, Carz v6.2, ProtocolLib v4.4.0, InvisibilityPlus v1.3, FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432, SensibleToolbox v4.9, WorldChangeScreenRemover v1.0.13, BuycraftX v11.0.0, LibsDisguises v9.7.1-SNAPSHOT, React v6.586, ServerlistMOTD vX-2018-10-19, Citizens v2.0.24-SNAPSHOT (build 1604), CommandNPC v1.9.1, TradeMe v6.0.0.3, SkyBlock v56, MiniBoardGames v3.3.10, QuickShop vReremake 1.3.5.2, QualityArmoryVehicles v1.0.34, BossShopPro v2.0.1, PlayerShops v1.2.3, LimitedUses v1.1.0, GuiShopManager v1.1.2, ItemShops v1.1.0, LeaderHeads v3.1.8.3, Duels v3.2.3, EpicAnchors v1.1.7, TNTRun_reloaded v7.5, SpigotLib v8.4, StarGate v9.3.1, BannerMaker v2.0.1, DiscordSRV v1.16.6, Residence v4.8.4.4, Griswold v0.083, Vault v1.7.1-b91, Stocks vv0.4.1, LotteryPool v1.4.0, CMIEInjector v1.0.2.1, EpicFurnaces v4.1.2, UltimateDrugs v1.1.5, PotionCreation v1.1.4, MoneyDrop v2.2.0
----------------------------------------------------------------------------------------------

More Information: 
Error reloading AutoPlay 1.2.15
NullPointerException (Unknown cause)
	 at me.kangarko.autoplay.goto.nul. .cOm1.Lpt5(SourceFile:110)
	 at me.kangarko.autoplay.goto.nul. .Aux.NUl(SourceFile:533)
	 at me.kangarko.autoplay.goto.nul. .Aux.lpt5(SourceFile:499)
	 at me.kangarko.autoplay.command.ReloadCommand.handleSubCommand(SourceFile:22)
	 at me.kangarko.autoplay.goto.nul. .lPT9.handleCommand(SourceFile:172)
	 at me.kangarko.autoplay.goto.nul. .cOM6.onCommand(SourceFile:61)
	 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702)
----------------------------------------------------------------------------------------------


------------------------------------[ 02.02.2019 17:39:24 ]-----------------------------------
AutoPlay 1.2.15 encountered a NullPointerException
Running CraftBukkit 1.13.2-R0.1-SNAPSHOT and Java 10.0.2
Plugins: RedstoneProximitySensor v2.3.9, PlayerInteractions v1.0, BlockLocker v1.5, InfinityParkour v1.0.10, Lift v${version}, PlugMan v2.1.5, ChestSort v3.4, Recount v3.3.0, Arconix v2.0.0, TermsOfUse v1.0.0, GameAPI v1.3.5, RedstoneWaterProof v1.0 BETA, SaveRod v2.4.1, AutoPlay v1.2.15, LuckPerms v4.3.73, EasyBackup v2.8.1, DeathMessagesPrime v1.13.12, ImageMaps v0.4.5, VotingPlugin v5.17.4, FastAsyncWorldEdit v1.0, VoidGenerator v1.4.2, PerWorldPluginsPremium v1.7.5, PixelFriends v1.0, PluginConstructorAPI v1.0.50, PlayerProfiles v1.0, McWiki v2.5.1, ChatColor2 v1.7.6, PlaceholderAPI v2.9.2, AdditionsAPI v1.3.2, NametagEdit v4.4.0, TreasureHunt v3.0.5, VanillaAdditions v1.3.3, NoteBlockAPI v1.2.5, LightAPI v3.2.9, JukeBox v1.10.1, CoreProtect v2.15.1, dynmap v3.0-beta-3-160, WorldEdit v7.0.0-SNAPSHOT;4007-f3ec5bb, CityWorld v4.04, WorldBorder v1.8.7, EpicFarming v2.0.19, Votifier v2.5.0, BannerBoard v1.9.10.4, HeadsPlus v5.4, YoutubeMC v1.0, ServerMinimap v0.7.18, CS-CoreLib v9, HoloDrops v1.6, AdditionalThings v1.4.2, XrayInformer v3.7.0, The Multiverse-Core Plugin, Slimefun v9, StockPlus v1.0.13, CoreArena v1.8.1, ExtraGear v1.1.1, ExoticGarden v1.8.0, Barrels v1.12, SlimefunCustomizer v1.2.3, SlimeXpansion v1.1.11, UltimateTimber v1.0.9, ElectricSpawners v4.1, AuthMe v5.5.1-SNAPSHOT-b2200, PictureLogin v1.5, SuperLuckyBlock-Pro v2.17.1, HolographicDisplays v2.3.2, CMI v8.3.9.4, SpeechBubblesNG v1.1.1, QualityArmory v1.1.135, SelectionVisualizer v2.0.2.0, TwitchSync v1.4, GadgetsMenu v4.3.4, Jobs v4.9.5, Paintball v2.2.0, MobCapture v1.2.6, Carz v6.2, ProtocolLib v4.4.0, InvisibilityPlus v1.3, FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432, SensibleToolbox v4.9, WorldChangeScreenRemover v1.0.13, BuycraftX v11.0.0, LibsDisguises v9.7.1-SNAPSHOT, React v6.589, ServerlistMOTD vX-2018-10-19, Citizens v2.0.24-SNAPSHOT (build 1604), CommandNPC v1.9.1, TradeMe v6.0.0.3, SkyBlock v56, MiniBoardGames v3.3.10, QuickShop vReremake 1.3.5.2, QualityArmoryVehicles v1.0.34, BossShopPro v2.0.1, PlayerShops v1.2.3, LimitedUses v1.1.0, GuiShopManager v1.1.2, ItemShops v1.1.0, LeaderHeads v3.1.8.3, Duels v3.2.3, EpicAnchors v1.1.7, TNTRun_reloaded v7.5, SpigotLib v8.4, StarGate v9.3.1, BannerMaker v2.0.1, DiscordSRV v1.16.6, Residence v4.8.4.4, Griswold v0.083, Vault v1.7.1-b91, Stocks vv0.4.1, LotteryPool v1.4.0, CMIEInjector v1.0.2.1, EpicFurnaces v4.1.2, UltimateDrugs v1.1.5, PotionCreation v1.1.4, MoneyDrop v2.2.0
----------------------------------------------------------------------------------------------

More Information: 
Error reloading AutoPlay 1.2.15
NullPointerException (Unknown cause)
	 at me.kangarko.autoplay.goto.nul. .cOm1.Lpt5(SourceFile:110)
	 at me.kangarko.autoplay.goto.nul. .Aux.NUl(SourceFile:533)
	 at me.kangarko.autoplay.goto.nul. .Aux.lpt5(SourceFile:499)
	 at me.kangarko.autoplay.command.ReloadCommand.handleSubCommand(SourceFile:22)
	 at me.kangarko.autoplay.goto.nul. .lPT9.handleCommand(SourceFile:172)
	 at me.kangarko.autoplay.goto.nul. .cOM6.onCommand(SourceFile:61)
	 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702)
----------------------------------------------------------------------------------------------
```

**Comment by MothGirlMusic** [comment]
looks like it doesn't like me quoting code. here's the entire issue in paste bin to help: https://pastebin.com/Su66vVPY

**Comment by MothGirlMusic** [comment]
left clicking with the lobby setting tool does nothing as well. no errors in console until you right click.

and then you get the obvious "lobby not set"... but i can't set the lobby because the tool doesn't  work...

[18:22:39 INFO]: AutoPlay // AutoPlay 1.2.15 encountered a COM4! Please check your error.log and report this issue with the information in that file.
[18:22:39 WARN]: me.kangarko.autoplay.goto.nul. .COM4: Report / Wait lobby not set

**Comment by kangarko** [comment]
Hey,

sorry for the delay. You can configure the World in the Rotation Menu, just do `/ap menu` (https://i.imgur.com/o6I1cvF.png).

For the errors, I am checking them right now.

**Comment by kangarko** [comment]
Please try to do following steps:

1. Remove the entire AutoPlay folder to start fresh.
2. Set Mode to world in settings.yml
3. Restart.
4. Go to game, get the Selection tool from /ap tools, go to your world and set a point there.
5. Restart. The rotation should load.
6. Open /ap menu and select your world and arenas. Now you should be able to start the rotation.

If any additional errors or problems arise please post them below. Thank you.

**Comment by MothGirlMusic** [comment]
exact same error i posted when using the tool. being that i've already posted the error above i'll post a screen shot of me using the tool.
<img width="675" alt="screen shot 2019-02-12 at 11 42 44 am" src="https://user-images.githubusercontent.com/1746550/52652101-777db580-2ebb-11e9-9fee-841217c06a11.png">

**Comment by MothGirlMusic** [comment]
no rotation loaded and the /ap menu does not have a world in it.

**Comment by kangarko** [comment]
I am investigating this.

Can you try repeating the process without using **/ap reload** or **/reload** nor PlugMan?

**Comment by MothGirlMusic** [comment]
i didn't use any of those commands to set it up

**Comment by MothGirlMusic** [comment]
this is my config if that helps: https://pastebin.com/enbEUt2W

**Comment by MothGirlMusic** [comment]
ok on the latest version you just uploaded... setting "Mode: world" is not supported anymore? spawning in the tools from /ap menu now spawns a normal golden hoe... and using it just damages it like normal... the menu complains about wanting me to set world mode in settings. which i've already done.

**Comment by kangarko** [comment]
Hey, please test the next version. If any errors occur please make sure to post them again because the line numbers have been changed. I just tested with the Golden Tool and it worked fine on the next version.

Make sure the Mode is set to "world" exactly:

![a](https://i.imgur.com/hAzhWNK.png)

**Comment by MothGirlMusic** [comment]
it never worked for me. i'm abandoning it since your latest update on it says youre abandoning support on it anyway

**Comment by kangarko** [comment]
Alright sorry about that.
